version: '3.8'
services:
  bot-app:
    container_name: bot-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
